### ISSUE TITLE
unix build not successful

### ISSUE THREAD

**Issue by sannykr** [conda-forge/newrelic-feedstock#9]
I tried to upgrade the package on conda forge, but it seems unix build was not successful. Could you please retrigger the build. Do I need to rerender the feedstock?

**Comment by sannykr** [comment]
@synapticarbors : Although all checks passed when I made a pull request, it failed to build for linux after merging to the master. Will it be helpful if feedstock is rerendered?

**Comment by synapticarbors** [comment]
It looks like it was maybe a connection issue. Either @bollwyvl can go to:

https://circleci.com/gh/conda-forge/newrelic-feedstock/16

and try to rebuild, or you can also put in a PR to re-render

**Comment by sannykr** [comment]
@bollwyvl : Could you please trigger the build again.

**Comment by bollwyvl** [comment]
Looks like we've been getting linux builds for a while....
